BATCH_SIZE=32
DISTIL_BERT_MODEL="distilbert-base-uncased"
BERT_MAX_TOKENS = 256
BERT_EMBEDDING_SIZE = 768

CLIP_TEXT_CONTEXT_SIZE = 77
CLIP_TEXT_EMB_SIZE = 512
CLIP_IMG_EMB_SIZE = 512
FACE_EMBEDDING_SIZE=512